version: "3.9"
services:
  metering:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 8080
      BINDINGS: '[{"sku_id": "sku", "product_id": "product"}]'
      MODE: 'always'
    ports:
      - 8080:8080
